### ISSUE TITLE
How are the scales defined? 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/gapminder#20]
In this and many other examples: 

![image](https://cloud.githubusercontent.com/assets/2039375/11641694/e9295568-9cf6-11e5-81bc-51bedab044d2.png)

It's unclear to me why there is that much whitespace. I realize that sometimes this is to not have to rescale the axis as we move over the time slider, but here I can't see the point that does that anywhere.

**Comment by sgratzl** [comment]
in the gdp case: 1980 - United Arab Emirates: 182,668 max
