### ISSUE TITLE
Presentation Mode: Move automatically generated annotation

### ISSUE THREAD

**Issue by NicolaLady** [Caleydo/gapminder#36]
- in pres mode the annotation is obscured by the timeline at the bottom 
- either hide the timeline in presentation mode as it is read only anyhu and the year text label informs us of what year we are in too so not really needed.
- or could just have the automatically generated annotation positioned at the top, center of the chart 

<img width="1309" alt="screen shot 2015-12-09 at 12 50 58" src="https://cloud.githubusercontent.com/assets/5597516/11684658/853df2f6-9e73-11e5-952e-69cf36459c8d.png">

**Comment by sgratzl** [comment]
I removed the subtitles as the moment
