### ISSUE TITLE
Annotations using Text tool on the Chart are disappearing

### ISSUE THREAD

**Issue by NicolaLady** [Caleydo/gapminder#37]
- annotations are disappearing after they are created
- for example here, I had annotated the chart with some text where the arrow is but its disappeared after i moved to a different state in story board in presentation

<img width="784" alt="screen shot 2015-12-10 at 09 50 31" src="https://cloud.githubusercontent.com/assets/5597516/11710963/7ac43b4a-9f23-11e5-8f99-c727c76dbd8a.png">

**Comment by NicolaLady** [comment]
- I am in authoring mode and on currently selected state "Health and Wealth in 2015 for all continents"   00:13
- i click on the annotation toolbar and create a new text annotation "Overall trend...."
  <img width="1294" alt="screen shot 2015-12-10 at 18 44 49" src="https://cloud.githubusercontent.com/assets/5597516/11723782/6813d76a-9f70-11e5-925e-13c160738d0d.png">
- I now want to create another annotation below this one but when i click on the text annotation tool the annotation just created disappears / is over written

<img width="1293" alt="screen shot 2015-12-10 at 18 45 02" src="https://cloud.githubusercontent.com/assets/5597516/11723787/6e0fdbd2-9f70-11e5-8a7b-97edf52c188a.png">

**Comment by sgratzl** [comment]
please try again
