### ISSUE TITLE
Logo is not displayed correctly

### ISSUE THREAD

**Issue by dvvanessastoiber** [Caleydo/gapminder#76]
* Release number or git hash: 01b4324a5d8c4af04eba37c51a96b882a909dba2
* Web browser version and OS: Chrome 81, Linux
* Environment (local or deployed): both

### Steps to reproduce

1. Open https://gapminder.caleydoapp.org/
2. Click on the `i` button in the navigation bar

### Observed behavior
* Logo on the bottom left is not visible (SVG)
![image](https://user-images.githubusercontent.com/52395160/80342112-e26aa080-8863-11ea-8fe8-2891543c8884.png)
* this issue is likely to be related with webpack loaders

### Expected behavior
* Logo is loaded correctly

**Comment by thinkh** [comment]
Seems to work with the current develop version.

![grafik](https://user-images.githubusercontent.com/5851088/100727062-0aa41a00-33c6-11eb-9161-b315a8991071.png)
